In [30]:
import pandas as pd

# Trending Tickers Yahoo Finance

In [31]:
df=pd.read_excel("yahoo_tickers.xlsx")
print(len(df))
df.head()

20728

,Ticker,Name,Exchange,Category Name,Country
0,AAPL,Apple Inc.,NMS,Electronic Equipment,USA
1,BAC,Bank of America Corporation,NYQ,Money Center Banks,USA
2,AMZN,"Amazon.com, Inc.",NMS,Catalog & Mail Order Houses,USA
3,T,AT&T Inc.,NYQ,Telecom Services - Domestic,USA
4,GOOG,Alphabet Inc.,NMS,Internet Information Providers,USA

In [32]:
lst_tickers=list(df["Ticker"])

In [33]:
df1=pd.read_csv("first101.csv")
df1=df1.drop(["MaxAge"],axis=1)
df1.head()

,Sector,Industry,Currency,Market,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Symbol,Name,Exchange,Country
0,Technology,Consumer Electronics,USD,us_market,38,2086460850176,1.354002,2,AAPL,Apple Inc.,NMS,USA
1,Financial Services,Banks—Diversified,USD,us_market,25,248191172608,1.571589,2.4,BAC,Bank of America Corporation,NYQ,USA
2,Consumer Cyclical,Internet Retail,USD,us_market,46,1615678406656,1.298759,1.7,AMZN,"Amazon.com, Inc.",NMS,USA
3,Communication Services,Telecom Services,USD,us_market,27,205727629312,0.673618,2.8,T,AT&T Inc.,NYQ,USA
4,Communication Services,Internet Content & Information,USD,us_market,12,1214037491712,1.023111,1.6,GOOG,Alphabet Inc.,NMS,USA

In [34]:
df2=pd.read_csv("101-201.csv")
df2["Ticker"]=lst_tickers[101:201]
df2.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,"Alnylam Pharmaceuticals, Inc.",USA,Healthcare,Biotechnology,USD,us_market,NMS,23,15367261184,1.590191,2,ALNY
1,Laboratory Corporation of America Holdings,USA,,,USD,us_market,NYQ,15,19622205440,1.195603,1.8,LH
2,Avery Dennison Corporation,USA,Industrials,Business Equipment & Supplies,USD,us_market,NYQ,11,12658635776,0.996054,2.4,AVY
3,Yamana Gold Inc.,USA,Basic Materials,Gold,USD,us_market,NYQ,12,5222050816,2.007147,2.6,AUY
4,Ashland Global Holdings Inc.,USA,Basic Materials,Chemicals,USD,us_market,NYQ,10,4614870016,1.401352,2.1,ASH

In [35]:
df3=pd.read_csv("201-301.csv")
df3["Ticker"]=lst_tickers[201:301]
df3.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Aeterna Zentaris Inc.,USA,Healthcare,Biotechnology,USD,us_market,NCM,,24113960,2.398141,,AEZS
1,"AcelRx Pharmaceuticals, Inc.",USA,Healthcare,Drug Manufacturers—Specialty & Generic,USD,us_market,NGM,5,132097296,1.519165,2,ACRX
2,Rockwell Automation Inc.,USA,Industrials,Specialty Industrial Machinery,USD,us_market,NYQ,22,28691566592,1.461104,2.8,ROK
3,"Gaming and Leisure Properties, Inc.",USA,Real Estate,REIT—Specialty,USD,us_market,NMS,16,9580493824,1.028184,1.8,GLPI
4,AZZ Inc.,USA,,Electrical Equipment & Parts,USD,us_market,NYQ,2,1176827904,1.388951,1.7,AZZ

In [36]:
df4=pd.read_csv("301-401.csv")
df4["Ticker"]=lst_tickers[301:401]
df4.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,"Avid Technology, Inc.",USA,Communication Services,Electronic Gaming & Multimedia,USD,us_market,NMS,4,525192224,1.096956,2.4,AVID
1,"Ascena Retail Group, Inc.",USA,,,,us_market,NMS,,,,,ASNA
2,"On Assignment, Inc.",USA,Industrials,Staffing & Employment Services,USD,us_market,NYQ,7,4167461888,2.27452,2.1,ASGN
3,"Ardelyx, Inc.",USA,Healthcare,Biotechnology,USD,us_market,NGM,5,553223296,2,1.3,ARDX
4,Accuray Incorporated,USA,Healthcare,Medical Devices,USD,us_market,NMS,,386087744,1.794813,1.5,ARAY

In [37]:
df5=pd.read_csv("401-501.csv")
df5["Ticker"]=lst_tickers[401:501]
df5.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Alliant Energy Corporation,USA,Utilities,Utilities—Regulated Electric,USD,us_market,NYQ,8,13329743872,0.366967,2.1,LNT
1,Kaiser Aluminum Corporation,USA,Basic Materials,Aluminum,USD,us_market,NMS,1,1384674304,1.071589,3,KALU
2,"Home Bancshares, Inc. (Conway, AR)",USA,Financial Services,Banks—Regional,USD,us_market,NMS,8,3123326976,1.527621,2,HOMB
3,First American Financial Corporation,USA,Financial Services,Insurance—Specialty,USD,us_market,NYQ,5,5430412800,1.180947,2.3,FAF
4,First Acceptance Corporation,USA,,,,us_market,NYQ,,,,,FAC

In [38]:
df6=pd.read_csv("501-601.csv")
df6["Ticker"]=lst_tickers[501:601]
df6.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Authentidate Holding Corp.,USA,,,,us_market,PNK,,,,,ADAT
1,Adaptimmune Therapeutics plc,USA,Healthcare,Biotechnology,USD,us_market,NMS,6,735200256,2.478015,2.4,ADAP
2,Acme United Corporation,USA,Consumer Defensive,Household & Personal Products,USD,us_market,ASE,1,112087208,1.021984,1,ACU
3,WestJet Airlines Ltd.,Canada,,,,us_market,TOR,,,,,WJA.TO
4,Turkcell Iletisim Hizmetleri A.S.,USA,Communication Services,Telecom Services,TRY,us_market,NYQ,3,4230724864,0.777917,2.3,TKC

In [39]:
df7=pd.read_csv("601-701.csv")
df7["Ticker"]=lst_tickers[601:701]
df7.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,"Air T, Inc.",USA,Industrials,Integrated Freight & Logistics,USD,au_market,NCM,,31988536,1.131341,,AIRT
1,Accor SA,France,Consumer Cyclical,Lodging,EUR,au_market,PAR,15,7708185088,1.255696,,AC.PA
2,Anheuser-Busch InBev SA/NV,Belgium,Consumer Defensive,Beverages—Brewers,USD,au_market,BRU,27,110065500160,1.134177,,ABI.BR
3,XRF Scientific Limited,Australia,Technology,Scientific & Technical Instruments,AUD,au_market,ASX,1,41713908,0.70886,,XRF.AX
4,Woolworths Limited,Australia,Consumer Defensive,Grocery Stores,AUD,au_market,ASX,12,47881224192,0.329746,,WOW.AX

In [40]:
df8=pd.read_csv("701-801.csv")
df8["Ticker"]=lst_tickers[701:801]
df8.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,InVision Aktiengesellschaft,Germany,Technology,Software—Application,,au_market,GER,,42465000,1.303797,,IVX.DE
1,Integrated Research Limited,Australia,Technology,Software—Application,AUD,au_market,ASX,2,583673280,0.930379,,IRI.AX
2,Alamo Energy Corp.,USA,Energy,Oil & Gas E&P,USD,au_market,PNK,,45345,51.623447,,ALME
3,Haldex AB (publ),Sweden,Consumer Cyclical,Auto Parts,SEK,au_market,STO,2,1910985984,1.70443,,HLDX.ST
4,Hills Limited,Australia,Industrials,Security & Protection Services,AUD,au_market,ASX,1,42917412,0.88481,,HIL.AX

In [41]:
df9=pd.read_csv("801-901.csv")
df9["Ticker"]=lst_tickers[801:901]
df9.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Interoil Exploration and Production ASA,Norway,Energy,Oil & Gas E&P,USD,au_market,OSL,1,179109952,,5,IOX.OL
1,Imugene Limited,Australia,Healthcare,Biotechnology,AUD,au_market,ASX,,574722496,0.782911,,IMU.AX
2,Iluka Resources Limited,Australia,Basic Materials,Other Industrial Metals & Mining,AUD,au_market,ASX,7,2270274816,1.543037,,ILU.AX
3,High Arctic Energy Services Inc,Canada,Energy,Oil & Gas Equipment & Services,CAD,au_market,TOR,1,50760008,2.197283,3,HWO.TO
4,Harvey Norman Holdings Limited,Australia,Consumer Cyclical,Department Stores,AUD,au_market,ASX,9,5843786752,0.742405,,HVN.AX

In [42]:
df10=pd.read_csv("901-1001.csv")
df10["Ticker"]=lst_tickers[901:1001]
df10.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,"PASSUR Aerospace, Inc.",USA,Industrials,Aerospace & Defense,USD,no_market,PNK,,2467868,0.049605,,PSSR
1,Petsec Energy Ltd,Australia,Energy,Oil & Gas E&P,USD,no_market,ASX,,8580348,0.991139,3,PSA.AX
2,Perpetual Limited,Australia,Financial Services,Asset Management,AUD,no_market,ASX,10,1920175744,1.383544,,PPT.AX
3,PNE Wind AG,Germany,Utilities,Utilities—Renewable,EUR,no_market,GER,4,596951424,0.701265,,PNE3.DE
4,Premier Investments Limited,Australia,Consumer Cyclical,Apparel Retail,AUD,no_market,ASX,10,3639574272,1.250632,,PMV.AX

In [43]:
other=pd.read_csv("other.csv")
other.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Microsoft Corporation,United States,Technology,Software—Infrastructure,USD,us_market,NMS,31,1628304834560,0.823097,1.7,MSFT
1,Apple Inc.,United States,Technology,Consumer Electronics,USD,us_market,NMS,38,2092581519360,1.354002,2,AAPL
2,"Advanced Micro Devices, Inc.",,Technology,Semiconductors,USD,us_market,NMS,33,112742031360,2.267191,2.3,AMD
3,Walt Disney Company (The),,Communication Services,Entertainment,USD,us_market,NYQ,24,278107848704,1.075535,2,DIS
4,"Invesco QQQ Trust, Series 1",,,,,us_market,NMS,,119443439616,,,QQQ

In [44]:
df1.columns

Index(['Sector', 'Industry', 'Currency', 'Market', 'Nber_of_analyst_opinions',
       'MarketCap', 'Volatility', 'Recommendation_mean', 'Symbol', 'Name',
       'Exchange', 'Country'],
      dtype='object')

In [45]:
df2.columns

Index(['Name', 'Country', 'Sector', 'Industry', 'Currency', 'Market',
       'Exchange', 'Nber_of_analyst_opinions', 'MarketCap', 'Volatility',
       'Recommendation_mean', 'Ticker'],
      dtype='object')

In [46]:
df1=df1[['Name', 'Country', 'Sector', 'Industry', 'Currency', 'Market',
       'Exchange', 'Nber_of_analyst_opinions', 'MarketCap', 'Volatility',
       'Recommendation_mean', 'Symbol']]
df1.head()

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Symbol
0,Apple Inc.,USA,Technology,Consumer Electronics,USD,us_market,NMS,38,2086460850176,1.354002,2,AAPL
1,Bank of America Corporation,USA,Financial Services,Banks—Diversified,USD,us_market,NYQ,25,248191172608,1.571589,2.4,BAC
2,"Amazon.com, Inc.",USA,Consumer Cyclical,Internet Retail,USD,us_market,NMS,46,1615678406656,1.298759,1.7,AMZN
3,AT&T Inc.,USA,Communication Services,Telecom Services,USD,us_market,NYQ,27,205727629312,0.673618,2.8,T
4,Alphabet Inc.,USA,Communication Services,Internet Content & Information,USD,us_market,NMS,12,1214037491712,1.023111,1.6,GOOG

In [47]:
df1.columns=df2.columns

In [48]:
data=pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10,other], axis=0, ignore_index=True)

data.head(100)

,Name,Country,Sector,Industry,Currency,Market,Exchange,Nber_of_analyst_opinions,MarketCap,Volatility,Recommendation_mean,Ticker
0,Apple Inc.,USA,Technology,Consumer Electronics,USD,us_market,NMS,38,2086460850176,1.354002,2,AAPL
1,Bank of America Corporation,USA,Financial Services,Banks—Diversified,USD,us_market,NYQ,25,248191172608,1.571589,2.4,BAC
2,"Amazon.com, Inc.",USA,Consumer Cyclical,Internet Retail,USD,us_market,NMS,46,1615678406656,1.298759,1.7,AMZN
3,AT&T Inc.,USA,Communication Services,Telecom Services,USD,us_market,NYQ,27,205727629312,0.673618,2.8,T
4,Alphabet Inc.,USA,Communication Services,Internet Content & Information,USD,us_market,NMS,12,1214037491712,1.023111,1.6,GOOG
...,...,...,...,...,...,...,...,...,...,...,...,...
95,"AmTrust Financial Services, Inc.",USA,,,,us_market,NMS,,,,,AFSI
96,AmerisourceBergen Corporation,USA,Healthcare,Medical Distribution,USD,us_market,NYQ,16,20872308736,0.549605,2.4,ABC
97,Statoil ASA,USA,,,,us_market,NYQ,,,,,STO
98,Allegheny Technologies Incorporated,USA,Industrials,Metal Fabrication,USD,us_market,NYQ,7,1781764864,1.656144,3.2,ATI
99,"AvalonBay Communities, Inc.",USA,Real Estate,REIT—Residential,USD,us_market,NYQ,18,23377524736,0.896279,2.7,AVB

# Cleaning the Data

In [49]:
len(data)

1032

In [52]:
data=data.drop_duplicates("Ticker")

In [53]:
len(data)

1026

In [54]:
import tkinter as tk
from tkinter import filedialog
from pandas import DataFrame

root= tk.Tk()

canvas1 = tk.Canvas(root, width = 300, height = 300, bg = 'lightsteelblue2', relief = 'raised')
canvas1.pack()

def exportCSV ():
    global df
    
    export_file_path = filedialog.asksaveasfilename(defaultextension='.csv')
    data.to_csv (export_file_path, index = False, header=True)

saveAsButton_CSV = tk.Button(text='Export CSV', command=exportCSV, bg='green', fg='white', font=('helvetica', 12, 'bold'))
canvas1.create_window(150, 150, window=saveAsButton_CSV)

root.mainloop()